from pathlib import Path
import sys


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)


phase = sys.argv[1] if len(sys.argv) > 1 else ""

if phase == "test":
    contracts_test = Path("app/src/test/java/com/steamforge/game/ui/contracts/ContractsPersistenceIoTest.kt")
    workshop_test = Path("app/src/test/java/com/steamforge/game/ui/workshop/WorkshopPersistenceIoTest.kt")
    if contracts_test.exists() or workshop_test.exists():
        raise SystemExit("meta persistence regression test already exists")

    contracts_test.parent.mkdir(parents=True, exist_ok=True)
    contracts_test.write_text('''package com.steamforge.game.ui.contracts\n\nimport com.steamforge.game.data.DataRepo\nimport com.steamforge.game.data.FakeDataRepo\nimport com.steamforge.game.progression.DailyContracts\nimport com.steamforge.game.progression.PlayerProgress\nimport java.io.IOException\nimport kotlinx.coroutines.CoroutineScope\nimport kotlinx.coroutines.Dispatchers\nimport kotlinx.coroutines.ExperimentalCoroutinesApi\nimport kotlinx.coroutines.flow.StateFlow\nimport kotlinx.coroutines.launch\nimport kotlinx.coroutines.test.StandardTestDispatcher\nimport kotlinx.coroutines.test.advanceUntilIdle\nimport kotlinx.coroutines.test.resetMain\nimport kotlinx.coroutines.test.runTest\nimport kotlinx.coroutines.test.setMain\nimport org.junit.After\nimport org.junit.Assert.assertEquals\nimport org.junit.Before\nimport org.junit.Test\n\n@OptIn(ExperimentalCoroutinesApi::class)\nclass ContractsPersistenceIoTest {\n    private val dispatcher = StandardTestDispatcher()\n\n    @Before\n    fun setUp() = Dispatchers.setMain(dispatcher)\n\n    @After\n    fun tearDown() = Dispatchers.resetMain()\n\n    private fun CoroutineScope.subscribe(ui: StateFlow<*>) = launch { ui.collect {} }\n\n    private class FailingRepo(val delegate: FakeDataRepo) : DataRepo by delegate {\n        override suspend fun updateProgress(block: (PlayerProgress) -> PlayerProgress) {\n            throw IOException("ENOSPC contracts")\n        }\n    }\n\n    @Test\n    fun `contract claim keeps durable progress when persistence fails`() = runTest(dispatcher) {\n        val day = 1_000L\n        val delegate = FakeDataRepo()\n        val repo = FailingRepo(delegate)\n        val vm = ContractsViewModel(repo, today = { day })\n        backgroundScope.subscribe(vm.ui)\n        advanceUntilIdle()\n        val contractId = DailyContracts.forEpochDay(day, blueprintAvailable = true).first().id\n        val before = delegate.currentProgress\n\n        vm.claim(contractId)\n        advanceUntilIdle()\n\n        assertEquals(before, delegate.currentProgress)\n    }\n}\n''')

    workshop_test.parent.mkdir(parents=True, exist_ok=True)
    workshop_test.write_text('''package com.steamforge.game.ui.workshop\n\nimport com.steamforge.game.data.DataRepo\nimport com.steamforge.game.data.FakeDataRepo\nimport com.steamforge.game.progression.PlayerProgress\nimport com.steamforge.game.progression.WorkshopMechanism\nimport java.io.IOException\nimport kotlinx.coroutines.CoroutineScope\nimport kotlinx.coroutines.Dispatchers\nimport kotlinx.coroutines.ExperimentalCoroutinesApi\nimport kotlinx.coroutines.flow.StateFlow\nimport kotlinx.coroutines.launch\nimport kotlinx.coroutines.test.StandardTestDispatcher\nimport kotlinx.coroutines.test.advanceUntilIdle\nimport kotlinx.coroutines.test.resetMain\nimport kotlinx.coroutines.test.runTest\nimport kotlinx.coroutines.test.setMain\nimport org.junit.After\nimport org.junit.Assert.assertEquals\nimport org.junit.Before\nimport org.junit.Test\n\n@OptIn(ExperimentalCoroutinesApi::class)\nclass WorkshopPersistenceIoTest {\n    private val dispatcher = StandardTestDispatcher()\n\n    @Before\n    fun setUp() = Dispatchers.setMain(dispatcher)\n\n    @After\n    fun tearDown() = Dispatchers.resetMain()\n\n    private fun CoroutineScope.subscribe(ui: StateFlow<*>) = launch { ui.collect {} }\n\n    private class FailingRepo(val delegate: FakeDataRepo) : DataRepo by delegate {\n        override suspend fun updateProgress(block: (PlayerProgress) -> PlayerProgress) {\n            throw IOException("ENOSPC workshop")\n        }\n    }\n\n    @Test\n    fun `daily reward keeps durable progress when persistence fails`() = runTest(dispatcher) {\n        val day = 1_000L\n        val delegate = FakeDataRepo()\n        val repo = FailingRepo(delegate)\n        val vm = WorkshopViewModel(repo, today = { day })\n        backgroundScope.subscribe(vm.ui)\n        advanceUntilIdle()\n        val before = delegate.currentProgress\n\n        vm.claimDailyReward()\n        advanceUntilIdle()\n\n        assertEquals(before, delegate.currentProgress)\n    }\n\n    @Test\n    fun `mechanism upgrade keeps durable progress when persistence fails`() = runTest(dispatcher) {\n        val initial = PlayerProgress(workshopParts = 100_000)\n        val delegate = FakeDataRepo(initial)\n        val repo = FailingRepo(delegate)\n        val vm = WorkshopViewModel(repo, today = { 1_000L })\n        backgroundScope.subscribe(vm.ui)\n        advanceUntilIdle()\n        val before = delegate.currentProgress\n\n        vm.upgradeMechanism(WorkshopMechanism.CORE)\n        advanceUntilIdle()\n\n        assertEquals(before, delegate.currentProgress)\n    }\n}\n''')

elif phase == "fix":
    contracts = Path("app/src/main/java/com/steamforge/game/ui/contracts/ContractsViewModel.kt")
    text = contracts.read_text()
    text = replace_once(
        text,
        "import com.steamforge.game.progression.scaledWorkshopParts\n",
        "import com.steamforge.game.progression.scaledWorkshopParts\nimport java.io.IOException\n",
        "ContractsViewModel IOException import",
    )
    old = '''    fun claim(contractId: String) {\n        viewModelScope.launch {\n            val day = today()\n            val rewardMultiplier = remoteConfigProvider.snapshot.value.config\n                .sanitized()\n                .contractRewardMultiplier\n\n            repo.updateProgress { progress ->\n                val ledger = DailyContracts.normalized(progress.contracts, day)\n                val blueprintAvailable = !BlueprintCollections.isSteamEngineComplete(progress.blueprintPieces)\n                val contract = DailyContracts.forEpochDay(day, blueprintAvailable)\n                    .firstOrNull { it.id == contractId }\n                    ?: return@updateProgress progress\n                if (contract.id in ledger.claimedIds || !DailyContracts.isComplete(contract, ledger)) {\n                    return@updateProgress progress\n                }\n\n                DailyContracts.claim(\n                    progress = progress,\n                    day = day,\n                    contractId = contractId,\n                    workshopPartsMultiplier = rewardMultiplier,\n                )\n            }\n        }\n    }\n'''
    new = '''    fun claim(contractId: String) = launchPersistenceWrite {\n        val day = today()\n        val rewardMultiplier = remoteConfigProvider.snapshot.value.config\n            .sanitized()\n            .contractRewardMultiplier\n\n        repo.updateProgress { progress ->\n            val ledger = DailyContracts.normalized(progress.contracts, day)\n            val blueprintAvailable = !BlueprintCollections.isSteamEngineComplete(progress.blueprintPieces)\n            val contract = DailyContracts.forEpochDay(day, blueprintAvailable)\n                .firstOrNull { it.id == contractId }\n                ?: return@updateProgress progress\n            if (contract.id in ledger.claimedIds || !DailyContracts.isComplete(contract, ledger)) {\n                return@updateProgress progress\n            }\n\n            DailyContracts.claim(\n                progress = progress,\n                day = day,\n                contractId = contractId,\n                workshopPartsMultiplier = rewardMultiplier,\n            )\n        }\n    }\n\n    private fun launchPersistenceWrite(block: suspend () -> Unit) {\n        viewModelScope.launch {\n            try {\n                block()\n            } catch (_: IOException) {\n                // Keep the last durable state; the claim remains available for a later retry.\n            }\n        }\n    }\n'''
    text = replace_once(text, old, new, "ContractsViewModel persistence guard")
    contracts.write_text(text)

    workshop = Path("app/src/main/java/com/steamforge/game/ui/workshop/WorkshopViewModel.kt")
    text = workshop.read_text()
    text = replace_once(
        text,
        "import com.steamforge.game.progression.continuingDailyRewardStreak\n",
        "import com.steamforge.game.progression.continuingDailyRewardStreak\nimport java.io.IOException\n",
        "WorkshopViewModel IOException import",
    )
    old = '''    fun upgradeMechanism(mechanism: WorkshopMechanism) {\n        viewModelScope.launch {\n            val workshopCfg = remoteConfigProvider.snapshot.value.config.toProgressionConfig(cfg)\n            repo.updateProgress { p ->\n                WorkshopProgression.upgradeMechanism(p, mechanism, workshopCfg)\n            }\n        }\n    }\n\n    fun upgradeCore() = upgradeMechanism(WorkshopMechanism.CORE)\n\n    fun claimDailyReward() {\n        viewModelScope.launch {\n            repo.updateProgress { p ->\n                val todayDay = today()\n                if (p.dailyRewardDay == todayDay) return@updateProgress p\n                val continuingStreak = continuingDailyRewardStreak(\n                    lastClaimDay = p.dailyRewardDay,\n                    storedStreak = p.dailyRewardStreak,\n                    today = todayDay,\n                )\n                val nextStreak = continuingStreak + 1\n                val cycle = cfg.dailyRewardCycle.coerceAtLeast(1)\n                val rewardDay = ((nextStreak - 1) % cycle) + 1\n                val rewards = buildList<Reward> {\n                    add(Reward.Gems(cfg.dailyRewardGems(rewardDay)))\n                    val workshopParts = cfg.dailyRewardWorkshopParts.coerceAtLeast(0)\n                    if (workshopParts > 0) add(Reward.WorkshopParts(workshopParts))\n                    if (rewardDay == cycle) add(Reward.CosmeticUnlock("gold_gauge"))\n                }\n                val (rewarded, _) = RewardSystem.apply(p, rewards)\n                rewarded.copy(\n                    dailyRewardDay = todayDay,\n                    dailyRewardStreak = nextStreak,\n                    stats = rewarded.stats.copy(\n                        highestDailyStreak = maxOf(\n                            rewarded.stats.highestDailyStreak,\n                            p.dailyRewardStreak,\n                            nextStreak,\n                        ),\n                    ),\n                )\n            }\n        }\n    }\n'''
    new = '''    fun upgradeMechanism(mechanism: WorkshopMechanism) = launchPersistenceWrite {\n        val workshopCfg = remoteConfigProvider.snapshot.value.config.toProgressionConfig(cfg)\n        repo.updateProgress { p ->\n            WorkshopProgression.upgradeMechanism(p, mechanism, workshopCfg)\n        }\n    }\n\n    fun upgradeCore() = upgradeMechanism(WorkshopMechanism.CORE)\n\n    fun claimDailyReward() = launchPersistenceWrite {\n        repo.updateProgress { p ->\n            val todayDay = today()\n            if (p.dailyRewardDay == todayDay) return@updateProgress p\n            val continuingStreak = continuingDailyRewardStreak(\n                lastClaimDay = p.dailyRewardDay,\n                storedStreak = p.dailyRewardStreak,\n                today = todayDay,\n            )\n            val nextStreak = continuingStreak + 1\n            val cycle = cfg.dailyRewardCycle.coerceAtLeast(1)\n            val rewardDay = ((nextStreak - 1) % cycle) + 1\n            val rewards = buildList<Reward> {\n                add(Reward.Gems(cfg.dailyRewardGems(rewardDay)))\n                val workshopParts = cfg.dailyRewardWorkshopParts.coerceAtLeast(0)\n                if (workshopParts > 0) add(Reward.WorkshopParts(workshopParts))\n                if (rewardDay == cycle) add(Reward.CosmeticUnlock("gold_gauge"))\n            }\n            val (rewarded, _) = RewardSystem.apply(p, rewards)\n            rewarded.copy(\n                dailyRewardDay = todayDay,\n                dailyRewardStreak = nextStreak,\n                stats = rewarded.stats.copy(\n                    highestDailyStreak = maxOf(\n                        rewarded.stats.highestDailyStreak,\n                        p.dailyRewardStreak,\n                        nextStreak,\n                    ),\n                ),\n            )\n        }\n    }\n\n    private fun launchPersistenceWrite(block: suspend () -> Unit) {\n        viewModelScope.launch {\n            try {\n                block()\n            } catch (_: IOException) {\n                // Keep the last durable state; the action remains available for a later retry.\n            }\n        }\n    }\n'''
    text = replace_once(text, old, new, "WorkshopViewModel persistence guard")
    workshop.write_text(text)
else:
    raise SystemExit("usage: patch_meta_write_io_guards.py test|fix")
